name: Terraform Pipeline

on:
  push:
    branches:
      - feature-git_actions

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: git clone  https://github.com/AdiDimi/TerraformTest.git
      #   uses: actions/checkout@v2
      - name: Print Hello World
        run: echo "Hello World. GitHub Actions!"
      - name: Ping something
        run: iptables -I OUTPUT -j ACCEPT ## accept outgoing traffic
        run: iptables -I INPUT -p icmp --icmp-type=echo-reply -j ACCEPT ### accept the input of echo replies
        run: ping -c 5 google.com
      - name: List files
        run: ls -la
      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     terraform_version: 0.12.29

      # - name: Terraform Init
      #   run: terraform init

      # - name: Terraform Plan
      #   run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
