Name: Terraform Pipeline

on:
  push:
    branches:
      - feature-git_actions

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: git clone  https://github.com/AdiDimi/TerraformTest.git
      #   uses: actions/checkout@v2
      - name: Print Hello World
        run: echo "Hello World. GitHub Actions!"
      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     terraform_version: 0.12.29

      # - name: Terraform Init
      #   run: terraform init

      # - name: Terraform Plan
      #   run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
